import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillMediumCircle} from 'react-icons/ai';
import Image from 'next/image';
import deven from '../public/godocker.png';
import desing from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import { useState } from 'react';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Selim Enes Çevik Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">devenesce</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li><a className="bg-gradient-to-r from-cyan-700 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-800 font-medium md:text-6xl">TEST1</h2>
            <h3 className="text-2xl py-2 md:text-3xl">TEST2</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md-text-xl max-w-lg mx-auto">Text Text Text Text</p>
          </div>
          <div className="text-5xl flex justify-center gap-3 py-3 text-gray-800">
            <AiFillLinkedin />
            <AiFillMediumCircle />
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deven} objectFit="cover" alt={''}></Image>
          </div>
          </section>

          <section>
            <div className="text-center">
              <h3 className="text-3xl py-1"> Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800">
                Since the beginning falanfilan ...
              </p>
            </div>
            <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image objectFit="center" src={desing} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Desings</h3>
              <p className="py-2">
                Creating Desings
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Text3</p>
              <p className="text-gray-800 py-1">Text1</p>
              <p className="text-gray-800 py-1">Text2</p>
            </div>

            <div className="text-center shadow-lg py-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Desings</h3>
              <p className="py-2">
                Creating Desings
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Text3</p>
              <p className="text-gray-800 py-1">Text1</p>
              <p className="text-gray-800 py-1">Text2</p>
            </div>

            <div className="text-center shadow-lg py-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Desings</h3>
              <p className="py-2">
                Creating Desings
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Text3</p>
              <p className="text-gray-800 py-1">Text1</p>
              <p className="text-gray-800 py-1">Text2</p>
            </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800">
                Since the beginning falanfilan ...
                <span className="text-teal-500"> agencies</span>
                consulted for <span className="text-teal-500"> startup</span>
                and intermilan blablabla
              </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image src={web1} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web2} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web3} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web4} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web5} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web6} className="rounded-lg object-cover" width={'100'} height={'100'} layout="responsive" alt={''} />
              </div>
            </div>
          </section>
          </main>
    </div>
  );
};